flags: {}
packages:
- '.'
# - location:
#     git: https://github.com/adscib/haskell-chart
#     commit: 021e5b2ce5b0ddb7c8a71569f8708330068fbf4a
#   subdirs:
#     - chart
#   extra-dep: true
# - location:
#     git: https://github.com/adscib/ad
#     commit: 658ee6968c15c55ae607d51e6fc2ac70e3e07920
#   extra-dep: true
- location:
    '../ad'
  extra-dep: true

extra-deps: []
resolver: lts-7.7
